"""Make the site's HTML compatible with a strict Content Security Policy.

1. Every inline style="..." attribute becomes a utility class (.u-N) defined in
   styles.css, so style-src no longer needs 'unsafe-inline'.
2. The one inline <script> (service preselect on quote.html) moves to js/preselect.js,
   so script-src no longer needs 'unsafe-inline' either.

Idempotent: re-running on already-clean pages changes nothing.
"""
import re, pathlib, sys

REPO = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".")
PAGES = sorted(REPO.glob("*.html"))
CSS = REPO / "styles.css"
MARK = "/* ===== utilities generated by harden.py (replace inline style attributes) ===== */"

# ---------- 1. inline styles -> classes ----------
styles = []
for p in PAGES:
    for m in re.finditer(r'\sstyle="([^"]*)"', p.read_text()):
        v = m.group(1).strip().rstrip(";")
        if v and v not in styles:
            styles.append(v)

css = CSS.read_text()
existing = {}
if MARK in css:                                    # keep numbering stable across runs
    for m in re.finditer(r'\.(u-\d+)\{(.*?)\}', css.split(MARK, 1)[1]):
        decl = ";".join(d.replace(" !important", "") for d in m.group(2).split(";") if d)
        existing[decl] = m.group(1)

cls = dict(existing)
n = len(existing)
for v in styles:
    if v not in cls:
        n += 1
        cls[v] = f"u-{n}"


def important(decls):
    out = []
    for d in decls.split(";"):
        d = d.strip()
        if d:
            out.append(d if d.endswith("!important") else d + " !important")
    return ";".join(out)


rules = "\n".join(f".{c}{{{important(v)}}}" for v, c in sorted(cls.items(), key=lambda kv: int(kv[1][2:])))
base = css.split(MARK, 1)[0].rstrip()
CSS.write_text(f"{base}\n\n{MARK}\n{rules}\n")


def fix_tag(m):
    tag = m.group(0)
    sm = re.search(r'\sstyle="([^"]*)"', tag)
    if not sm:
        return tag
    c = cls[sm.group(1).strip().rstrip(";")]
    tag = tag.replace(sm.group(0), "")
    if re.search(r'\sclass="', tag):
        tag = re.sub(r'\sclass="([^"]*)"', lambda k: f' class="{k.group(1)} {c}"', tag, count=1)
    else:
        tag = re.sub(r'^<([a-zA-Z][\w-]*)', lambda k: f'<{k.group(1)} class="{c}"', tag, count=1)
    return tag


# ---------- 2. inline script -> file ----------
PRESELECT_RE = re.compile(r'\n?<script>\s*/\* Service buttons live on detailing\.html.*?</script>\n?', re.S)
JS = REPO / "js" / "preselect.js"

for p in PAGES:
    s = p.read_text()
    s = re.sub(r'<[a-zA-Z][^<>]*\sstyle="[^"]*"[^<>]*>', fix_tag, s)
    m = PRESELECT_RE.search(s)
    if m:
        body = re.sub(r'^\s*<script>|</script>\s*$', '', m.group(0).strip()).strip()
        JS.parent.mkdir(exist_ok=True)
        JS.write_text(body + "\n")
        s = s.replace(m.group(0), '\n<script src="js/preselect.js" defer></script>\n')
    p.write_text(s)

# ---------- report ----------
left_style = sum(len(re.findall(r'\sstyle="', p.read_text())) for p in PAGES)
left_script = sum(len(re.findall(r'<script(?![^>]*\bsrc=)(?![^>]*ld\+json)[^>]*>', p.read_text())) for p in PAGES)
left_handlers = sum(len(re.findall(r'\son[a-z]+="', p.read_text())) for p in PAGES)
print(f"utility classes: {len(cls)}  | inline style left: {left_style}  "
      f"inline script left: {left_script}  inline handlers left: {left_handlers}")
